# SonarQube on OpenShift
This repo contains all of the resources required to build an OpenShift-specific Docker image of SonarQube 7.3.

NOTE: This documentation cover an environment using a private git repository, Container Native Storage (Gluster-based storage solution) and Satellite repository channels on Dockerfile for Red Hat Enterprise Linux 7.5 docker image. So, it's very important that you edit the template to adjust all the infos accordly with your environment, mainly the secret to import a private ssh-key if you also are using a private git repository.

## Step by step
Follow the tasks below to deploy SonarQube 7.3 on OpenShift environment:

[source,bash]
----
1. Create a new project:
oc adm new-project --node-selector=region=citools citools-sonarqube

2. Into the new project, deploy SonarQube from template:
oc new-app -f sonarqube-template.yaml

3. After that, add the secret created on step two for builder service account:
oc secrets add serviceaccount/builder secrets/sonarqube-ssh

4. Add the SCC (Security Context Constraints) privileged role for default service account:
oc adm policy add-scc-to-user privileged -z default

----

This will result in your OpenShift environment deploying the included PostgreSQL database with persistent storage and then deploying the SonarQube image directly from DockerHub. It will also set up a PersistentVolumeClaim for SonarQube to store plugins and other data.

Folow below all the objects included on template:

- Secret (ssh-auth) for private git repostory;
- BuildConfig for SonarQube 7.3 (Docker Strategy);
- ImageStream;
- PVCs for PostgreSQL and SonarQube;
- DeploymentConfig for PostgreSQL (Included ReadnessProbe/LivenessProbe/MemoryLimit);
- DeploymentConfig for SonarQube (Included ReadnessProbe/LivenessProbe/MemoryLimit/RequestLimit);
- Services for PostgreSQL and SonarQube;
- Route for SonarQube service;

---
forked from wkulhanek/docker-openshift-sonarqube. Thanks wkulhanek!!!
